---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Publish and Deploy
  image: sonarsource/sonar-scanner-cli
  #commands:
    #- sonar --help

    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
