---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Publish and Deploy
  image: gokgokalp/sonar-scanner-dotnetcore-msbuild
  #commands:
    #- dotnet sonarscanner begin /d:sonar.login=5d7f67176519a94f57416f1b02ec27628c9f7d75 /k:”HRIS-API”

    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
