---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Build
  image: burakince/docker-dotnet-sonarscanner
  commands:
     - --help
     - dotnet-scanner
    #- dotnet-scanner -it --rm -v $(pwd):/project -e PROJECT_KEY=ConsoleApplication1 -e PROJECT_NAME=ConsoleApplication1 -e PROJECT_VERSION=1.0 -e HOST=http://localhost:9000 -e LOGIN_KEY=CHANGE_THIS_ONE
    #- dotnet build
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
     - Dsonar
   
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
