---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - SonnarScanner.MSBuild.exe begin k:"HRIS-API" MSBuild.exe HRIS-API.sln /t:Rebuild
    - SonnarScanner.MSBuild.exe end
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
