---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Publish and Deploy
  image: mcr.microsoft.com/dotnet/sdk
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - dotnet 
    - dotnet "/drone/src/HRIS-API.sln" begin /k:"HRIS-API" /d:sonar.organization="cjmanaguelod1895" /d:sonar.host.url="$sonar_host" /d:sonar.login="$sonar_token"

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
