---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Build
  image: nosinovacao/dotnet-sonar
  commands:
     - dotnet /sonar-scanner/SonarScanner.MSBuild.dll begin /k:HRIS-API /o:cjmanaguelod1895 /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login="7053feaa49bfd77702a73e9bda280f5e9c16a6bd"
     - dotnet build
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
     - Dsonar
   
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
