---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - sonar-scanner
    - Sonar.Scanner begin /k:"HRIS-API" /o:"cjmanaguelod1895" /d:sonar.login="7053feaa49bfd77702a73e9bda280f5e9c16a6bd"
   
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
